module Kat
  NAME = 'Kickass Torrents Search'
  VERSION = '2.0.4'
  MALEVOLENT_DICTATOR_FOR_LIFE = 'Fission Xuiptz'
  AUTHOR = MALEVOLENT_DICTATOR_FOR_LIFE
  VERSION_STR = "#{NAME} #{VERSION} (c) 2013 #{MALEVOLENT_DICTATOR_FOR_LIFE}"
end
